server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location /api-docs/gateway {
    proxy_pass http://gateway:8080/v3/api-docs;
  }

  location /api-docs/identity-service {
    proxy_pass http://identity-service:8081/v3/api-docs;
  }

  location /api-docs/document-service {
    proxy_pass http://document-service:8082/v3/api-docs;
  }

  location /api-docs/metadata-service {
    proxy_pass http://metadata-service:8083/v3/api-docs;
  }

  location /api-docs/audit-service {
    proxy_pass http://audit-service:8084/v3/api-docs;
  }

  location /api-docs/search-service {
    proxy_pass http://search-service:8086/v3/api-docs;
  }
}
