
server:
  port: 8084

spring:
 datasource:
  url: jdbc:postgresql://postgres:5432/sgdea
  username: sgdea
  password: sgdea
 jpa:
  hibernate:
   ddl-auto: update

 kafka:
  bootstrap-servers: kafka:9092
  consumer:
   group-id: audit-service
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
   properties:
    spring.json.trusted.packages: "*"
    spring.json.value.default.type: java.util.HashMap

logging:
 level:
  root: INFO
 pattern:
  level: "%5p [traceId:%X{traceId:-N/A}] [otelTrace:%X{trace_id:-N/A}] [span:%X{span_id:-N/A}]"
