server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [traceId:%X{traceId:-N/A}] [otelTrace:%X{trace_id:-N/A}] [span:%X{span_id:-N/A}]"
