server:
  port: ${SERVER_PORT:8086}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [traceId:%X{traceId:-N/A}] [otelTrace:%X{trace_id:-N/A}] [span:%X{span_id:-N/A}]"
